import smtplib
from datetime import datetime
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from typing import Optional

from app.config import get_settings
from app.models.schemas import InterviewQuestion, ResumeAnalysis


def _send_email(to: str, subject: str, html_body: str) -> bool:
    settings = get_settings()
    if not settings.smtp_user or not settings.smtp_password:
        return False

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = settings.smtp_user
    msg["To"] = to
    msg.attach(MIMEText(html_body, "html"))

    with smtplib.SMTP(settings.smtp_host, settings.smtp_port) as server:
        server.starttls()
        server.login(settings.smtp_user, settings.smtp_password)
        server.sendmail(settings.smtp_user, [to], msg.as_string())
    return True


def _format_questions_html(questions: list[InterviewQuestion]) -> str:
    rows = []
    for i, q in enumerate(questions, 1):
        rationale = f"<br><em>Why: {q.rationale}</em>" if q.rationale else ""
        rows.append(
            f"<li><strong>[{q.category}]</strong> {q.question}{rationale}</li>"
        )
    return "<ol>" + "".join(rows) + "</ol>"


def send_candidate_interview_email(
    candidate_email: str,
    candidate_name: str,
    interview_datetime: datetime,
    interview_mode: str,
    job_role: str,
    meeting_link: Optional[str] = None,
    notes: Optional[str] = None,
) -> bool:
    settings = get_settings()
    dt_str = interview_datetime.strftime("%A, %B %d, %Y at %I:%M %p")
    link_block = (
        f'<p><strong>Meeting link:</strong> <a href="{meeting_link}">{meeting_link}</a></p>'
        if meeting_link
        else ""
    )
    notes_block = f"<p><strong>Notes:</strong> {notes}</p>" if notes else ""

    html = f"""
    <html><body style="font-family: Arial, sans-serif;">
    <h2>Interview Invitation — {settings.company_name}</h2>
    <p>Dear {candidate_name},</p>
    <p>Thank you for your application. We would like to invite you for an interview.</p>
    <ul>
      <li><strong>Role:</strong> {job_role}</li>
      <li><strong>Date &amp; Time:</strong> {dt_str}</li>
      <li><strong>Mode:</strong> {interview_mode}</li>
    </ul>
    {link_block}
    {notes_block}
    <p>Please confirm your availability by replying to this email.</p>
    <p>Best regards,<br>{settings.company_name}</p>
    </body></html>
    """
    subject = f"Interview Scheduled — {job_role} | {settings.company_name}"
    return _send_email(candidate_email, subject, html)


def send_hr_interview_pack(
    analysis: ResumeAnalysis,
    questions: list[InterviewQuestion],
    candidate_name: str,
    candidate_email: str,
    interview_datetime: datetime,
    job_role: str,
    interview_mode: str,
    meeting_link: Optional[str] = None,
) -> bool:
    settings = get_settings()
    if not settings.hr_email:
        return False

    dt_str = interview_datetime.strftime("%A, %B %d, %Y at %I:%M %p")
    skills = ", ".join(analysis.skills[:15]) if analysis.skills else "N/A"
    strengths = ", ".join(analysis.strengths) if analysis.strengths else "N/A"
    link_block = f"<p><strong>Meeting link:</strong> {meeting_link}</p>" if meeting_link else ""

    html = f"""
    <html><body style="font-family: Arial, sans-serif;">
    <h2>Interview Pack — {candidate_name}</h2>
    <h3>Schedule</h3>
    <ul>
      <li><strong>Candidate:</strong> {candidate_name} ({candidate_email})</li>
      <li><strong>Role:</strong> {job_role}</li>
      <li><strong>When:</strong> {dt_str}</li>
      <li><strong>Mode:</strong> {interview_mode}</li>
    </ul>
    {link_block}
    <h3>Resume Summary</h3>
    <p>{analysis.summary}</p>
    <p><strong>Skills:</strong> {skills}</p>
    <p><strong>Experience:</strong> {analysis.experience_years or "N/A"} years</p>
    <p><strong>Strengths:</strong> {strengths}</p>
    <h3>Suggested Interview Questions</h3>
    {_format_questions_html(questions)}
    <p><em>Generated by Recruitment Agent (Gemini).</em></p>
    </body></html>
    """
    subject = f"[HR] Interview Questions — {candidate_name} | {job_role}"
    return _send_email(settings.hr_email, subject, html)
